services:
  web:
    build: .
    command: ./start.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
