# Generated by Django 4.0.4 on 2025-06-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochat', '0003_alter_profile_photo_classrooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classrooms',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='classrooms',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classrooms',
            name='instructor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classrooms',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
