# Generated by Django 4.0.4 on 2025-06-16 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videochat', '0004_rename_created_at_classrooms_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrooms',
            name='owner',
        ),
        migrations.AddField(
            model_name='classrooms',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='classroom_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
