# Generated by Django 4.0.4 on 2025-06-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochat', '0005_remove_classrooms_owner_classrooms_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_pics/default-profile-img.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
